#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw($Bin);
use File::Basename qw(dirname);
use File::Temp qw(tempfile);

my @definitions = (
    "$Bin/rtl/includes/ctrl_signal_def.v",
    "$Bin/rtl/includes/instruction_def.v",
    "$Bin/rtl/includes/global_def.v",
);

my @sources = map { "$Bin/rtl/rtl/$_.v" } qw(
    ALU
    ControlUnit
    DM
    ExceptionUnit
    Flopr
    ForwardingUnit
    HazardUnit
    IDOperandSelector
    IDRedirectUnit
    IM
    InstructionFields
    InstructionDecoder
    NPC
    PC
    PipelineRegisters
    RF
    WishboneInstructionMaster
    WishboneLocalRouter
    WishboneMaster
    WishboneInstructionMemory
    WishboneDataMemory
    riscv
);

sub read_source {
    my ($path) = @_;
    open my $input, '<', $path or die "cannot open $path: $!\n";
    local $/;
    my $text = <$input>;
    close $input or die "cannot close $path: $!\n";
    $text =~ s/\r\n?/\n/g;
    return $text;
}

my $destination = $ARGV[0] // "$Bin/riscv.v";
my ($output, $temporary) = tempfile(
    'riscv.v.XXXXXX', DIR => dirname($destination), UNLINK => 0
);
my $flattened = "`timescale 1ns / 1ps\n";
$flattened .= "// Generated by flatten_rtl.pl from rtl/includes and rtl/rtl.\n\n";

for my $path (@definitions, @sources) {
    my $text = read_source($path);
    $text =~ s/^`timescale[^\n]*\n//mg;
    $text =~ s/^`include[^\n]*\n//mg;
    $text =~ s/\A\s+//;
    $text =~ s/\s+\z//;
    $flattened .= "// Source: " . ($path =~ s{^\Q$Bin/\E}{}r) . "\n";
    $flattened .= "$text\n\n";
}

$flattened =~ s/[ \t]+$//mg;
$flattened =~ s/\s+\z/\n/;
print {$output} $flattened;
close $output or die "cannot close $temporary: $!\n";
rename $temporary, $destination
    or die "cannot replace $destination: $!\n";
