`timescale 1ns / 1ps
// Generated by flatten_rtl.pl from rtl/includes and rtl/rtl.

// Source: rtl/includes/ctrl_signal_def.v
// NPC control signal
`define NPC_PC      2'b00
`define NPC_Offset12 2'b01
`define NPC_rs      2'b10
`define NPC_Offset20 2'b11

// A control signal
`define ALUSrcA_A    1'b0
`define ALUSrcA_sa   1'b1

// B control signal
`define ALUSrcB_B    2'b00
`define ALUSrcB_Imm  2'b01
`define ALUSrcB_Offset 2'b10
`define ALUSrcB_else 2'b11

// EXT control signal
`define ExtSel_ZERO  1'b0
`define ExtSel_SIGNED 1'b1

// ALU control signal
`define ALUOp_ADD   4'b0000
`define ALUOp_SUB   4'b0001
`define ALUOp_AND   4'b0010
`define ALUOp_OR    4'b0011
`define ALUOp_XOR   4'b0100
`define ALUOp_SRA   4'b0101
`define ALUOp_SLL   4'b1000
`define ALUOp_SRL   4'b1001
`define ALUOp_BR    4'b1010

// RF control signal
`define RegSel_rd    2'b00
`define RegSel_rt    2'b01
`define RegSel_31    2'b10
`define RegSel_else  2'b11

`define WDSel_FromALU 2'b00
`define WDSel_FromMEM 2'b01
`define WDSel_FromPC  2'b10
`define WDSel_Else    2'b11

// DM control signal
`define DMCtrl_RD    1'b0
`define DMCtrl_WR    1'b1

// RISC-V synchronous exception cause codes used by the minimal trap interface.
`define TRAP_INST_ADDR_MISALIGNED 4'd0
`define TRAP_INST_ACCESS_FAULT    4'd1
`define TRAP_ILLEGAL_INSTRUCTION  4'd2
`define TRAP_BREAKPOINT           4'd3
`define TRAP_LOAD_ADDR_MISALIGNED 4'd4
`define TRAP_LOAD_ACCESS_FAULT    4'd5
`define TRAP_STORE_ADDR_MISALIGNED 4'd6
`define TRAP_STORE_ACCESS_FAULT   4'd7

// Source: rtl/includes/instruction_def.v
//////////////////////////////////////////////////////////////////////////////////
// Company:
// Engineer:
//
// Create Date: 2024/11/20 19:50:15
// Design Name:
// Module Name: instruction_def
// Project Name:
// Target Devices:
// Tool Versions:
// Description:
//
// Dependencies:
//
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
//
//////////////////////////////////////////////////////////////////////////////////

// OPCODE
`define INSTR_RTYPE_OP      7'b0110011
`define INSTR_ITYPE_OP      7'b0010011
`define INSTR_BTYPE_OP      7'b1100011
`define INSTR_LW_OP         7'b0000011
`define INSTR_SW_OP         7'b0100011
`define INSTR_JAL_OP        7'b1101111
`define INSTR_JALR_OP       7'b1100111

// RÀàDÍ Funct ÒòÎªÖá
`define INSTR_ADD_FUNCT     10'b0000000_000
`define INSTR_SUB_FUNCT     10'b0100000_000
`define INSTR_SUBU_FUNCT    6'b100011
`define INSTR_AND_FUNCT     10'b0000000_111
`define INSTR_OR_FUNCT      10'b0000000_110
`define INSTR_XOR_FUNCT     10'b0000000_100
`define INSTR_NOR_FUNCT     6'b100111
`define INSTR_SLL_FUNCT     10'b0000000_001
`define INSTR_SRL_FUNCT     10'b0000000_101
`define INSTR_SRA_FUNCT     10'b0100000_101
`define INSTR_SRLV_FUNCT    6'b000110
`define INSTR_SRAV_FUNCT    6'b000111
`define INSTR_SLLV_FUNCT    6'b000100
`define INSTR_JR_FUNCT      6'b001000

// BÀàDÍ Funct ÒòÎªÖá
`define INSTR_BEQ_FUNCT     3'b000
`define INSTR_BNE_FUNCT     3'b001

// BÀàDÍ Funct ÒòÎªÖá
`define INSTR_ADDI_FUNCT    3'b000
`define INSTR_ORI_FUNCT     3'b110

// Source: rtl/includes/global_def.v
// `define DEBUG 1
//`define SRAM 1

// Source: rtl/rtl/ALU.v
module ALU(A,B,ALUOp,ALU_result);
    input signed [31:0] A;
    input signed [31:0] B;
    input [3:0] ALUOp;
    output reg signed [31:0] ALU_result;

wire [4:0] SHAMT;
wire [31:0] ADD_RESULT;
wire [31:0] SUB_RESULT;
wire signed [31:0] LOGIC_RESULT;
wire signed [31:0] SHIFT_RESULT;

assign SHAMT = B[4:0];

// Explicit prefix adders avoid the ripple implementation inferred for the
// DesignWare adders on the ALUOut critical path.
ALU_prefix_adder32 U_PREFIX_ADD (
    .A   (A),
    .B   (B),
    .CI  (1'b0),
    .SUM (ADD_RESULT)
);
ALU_prefix_adder32 U_PREFIX_SUB (
    .A   (A),
    .B   (~B),
    .CI  (1'b1),
    .SUM (SUB_RESULT)
);

assign LOGIC_RESULT =
    (ALUOp == `ALUOp_AND) ? (A & B) :
    (ALUOp == `ALUOp_OR)  ? (A | B) :
    (ALUOp == `ALUOp_XOR) ? (A ^ B) :
    32'sb0;

assign SHIFT_RESULT =
    (ALUOp == `ALUOp_SRA) ? (A >>> SHAMT) :
    (ALUOp == `ALUOp_SLL) ? (A << SHAMT) :
    (ALUOp == `ALUOp_SRL) ? $signed($unsigned(A) >> SHAMT) :
    32'sb0;

always @(*) begin

    case (ALUOp)
        `ALUOp_ADD: ALU_result = $signed(ADD_RESULT);
        `ALUOp_SUB: ALU_result = $signed(SUB_RESULT);
        `ALUOp_AND,
        `ALUOp_OR,
        `ALUOp_XOR: ALU_result = LOGIC_RESULT;
        `ALUOp_SRA,
        `ALUOp_SLL,
        `ALUOp_SRL: ALU_result = SHIFT_RESULT;
        default:    ALU_result = 32'sb0;
    endcase
end

endmodule

// 32-bit Kogge-Stone-style prefix adder with carry input.  The carry network
// has five prefix stages rather than a bit-by-bit ripple chain.
module ALU_prefix_adder32(A, B, CI, SUM);
    input  [31:0] A;
    input  [31:0] B;
    input         CI;
    output [31:0] SUM;

    wire [31:0] p0;
    wire [31:0] g0;
    wire [31:0] p1, g1;
    wire [31:0] p2, g2;
    wire [31:0] p3, g3;
    wire [31:0] p4, g4;
    wire [31:0] p5, g5;
    wire [31:0] carry;

    assign p0 = A ^ B;
    assign g0 = A & B;

    genvar i;
    generate
        for (i = 0; i < 32; i = i + 1) begin : GEN_PREFIX
            if (i < 1) begin
                assign p1[i] = p0[i];
                assign g1[i] = g0[i];
            end else begin
                assign p1[i] = p0[i] & p0[i-1];
                assign g1[i] = g0[i] | (p0[i] & g0[i-1]);
            end

            if (i < 2) begin
                assign p2[i] = p1[i];
                assign g2[i] = g1[i];
            end else begin
                assign p2[i] = p1[i] & p1[i-2];
                assign g2[i] = g1[i] | (p1[i] & g1[i-2]);
            end

            if (i < 4) begin
                assign p3[i] = p2[i];
                assign g3[i] = g2[i];
            end else begin
                assign p3[i] = p2[i] & p2[i-4];
                assign g3[i] = g2[i] | (p2[i] & g2[i-4]);
            end

            if (i < 8) begin
                assign p4[i] = p3[i];
                assign g4[i] = g3[i];
            end else begin
                assign p4[i] = p3[i] & p3[i-8];
                assign g4[i] = g3[i] | (p3[i] & g3[i-8]);
            end

            if (i < 16) begin
                assign p5[i] = p4[i];
                assign g5[i] = g4[i];
            end else begin
                assign p5[i] = p4[i] & p4[i-16];
                assign g5[i] = g4[i] | (p4[i] & g4[i-16]);
            end
        end

        for (i = 0; i < 32; i = i + 1) begin : GEN_SUM
            if (i == 0) begin
                assign carry[i] = CI;
            end else begin
                assign carry[i] = g5[i-1] | (p5[i-1] & CI);
            end
            assign SUM[i] = p0[i] ^ carry[i];
        end
    endgenerate
endmodule

// Source: rtl/rtl/ControlUnit.v
module ControlUnit(
    // control signal
    input rst,
    input clk,
    input [31:0] instruction,
    output reg PCWrite,
    output reg InsMemRW,
    output reg RFWrite,
    output reg DMCtrl,
    output reg [1:0] NPCOp,
    output reg [3:0] ALUOp,

    input [31:0] PC,
    input [31:0] PCA4,
    input [31:0] NPC,
    input [31:0] NPC_taken_p4,
    input [31:0] RD2,
    input [31:0] RD1_raw,
    input [31:0] RD2_raw,
    input [31:0] ALU_result,
    input [31:0] ALU_result_r,
    input [31:0] DM_RD,
    input [31:0] RD2_r,
    input        IF_ready,
    input        IF_error,
    input        DM_ready,
    input        DM_error,

    output reg mem_hold,
    output reg [31:0] PC_NPC,
    output reg [31:0] NPC_PC,
    output reg [31:0] FETCH_PC,
    output reg [19:0] NPC_EX_Offset20,
    output reg [11:0] NPC_EX_Offset12,
    output reg [4:0] WB_rd_out,
    output reg forward1,
    output reg forward2,
    output reg [31:0] FD1,
    output reg [31:0] FD2,
    output reg [31:0] EX_ALU_B,
    output reg [31:0] RF_WD,
    output reg [31:0] DM_WD,
    output wire       DMReq,
    output reg [4:0]  ID_rs1_out,
    output reg [4:0]  ID_rs2_out,
    output wire        trap,
    output wire [3:0]  trap_cause,
    output wire [31:0] trap_epc,
    output wire [31:0] trap_tval

    `ifdef DIFFTEST
    , output done
    `endif


);

`ifdef DIFFTEST
Flopr #(.WIDTH(1)) U_done (.clk(clk), .rst(rst), .in_data(WB_valid), .out_data(done));
`endif


/* #################################### pipeline signals #################################### */

/* IF */

wire        IF_stall;
wire [31:0] NPC_NPC, IM_PC;
reg         IF_PCWrite, IF_InsMemRW;


/* ID */
wire [31:0] ID_PCA4, ID_RD1, ID_RD2, ID_PC;
wire [11:0] ID_Imm12, ID_Offset;
wire [4:0]  ID_rs1, ID_rs2, ID_rd;
wire [3:0]  ID_ALUOp;
wire [1:0]  ID_ALUSrcB, ID_WDSel;
wire        ID_RFWrite, ID_DMCtrl;
wire        ID_valid;
wire        forward1_i, forward2_i;
wire [31:0] ID_control_RD1, ID_control_RD2;
wire [6:0]  ID_opcode;
wire [6:0]  ID_Funct7;
wire [2:0]  ID_Funct3;
wire [31:0] ID_ins;
wire        ID_illegal;
wire [1:0]  ID_NPCOp;

wire [19:0] ID_Offset20;

/* EX */
wire [31:0] EX_PCA4, EX_PC;
wire [19:0] EX_Offset20;
wire [11:0] EX_Offset;
wire [3:0]  EX_ALUOp;
wire [4:0]  EX_rd;
wire [1:0]  EX_WDSel, EX_NPCOp;
wire        EX_RFWrite, EX_DMCtrl;
wire        EX_valid;
wire        EX_branch;
wire        EX_redirect_predicted;
wire        EX_redirect;
wire        EX_redirect_wait;

/* MEM */
wire [31:0] MEM_WD, MEM_PCA4;
wire [31:0] MEM_writeback_data;
wire [4:0]  MEM_rd;
wire [1:0]  MEM_WDSel;
wire        MEM_RFWrite, MEM_DMCtrl;
wire        MEM_valid;

/* WB */
wire [31:0] WB_WD;
wire [4:0]  WB_rd;
wire        WB_RFWrite;
wire        WB_valid;
wire        pipe_flush;
wire        dec_valid;
wire        EX_exception;
wire        trap_request;
wire        EX_to_MEM_kill;
wire        IF_access_fault;
wire        ID_access_fault;
wire        MEM_access_fault;
wire        MEM_bus_wait;
wire        front_hazard_stall;
wire        IF_accept;
wire        IF_stage_valid;
wire [31:0] IF_stage_PC;
wire [31:0] IF_stage_PCA4;
wire [31:0] ID_ALU_B_sel;
wire [31:0] EX_ALU_B_sel;
wire [31:0] MEM_PC;
wire        MEM_load_ready;
wire        ID_control_transfer;
wire        ID_redirect;
wire [31:0] IF_stage_PCA4_sum;
wire [31:0] ID_redirect_target;

`ifdef DIFFTEST
reg [31:0] perf_if_wait_cycles;
reg [31:0] perf_load_hazard_cycles;
reg [31:0] perf_mem_wait_cycles;
reg [31:0] perf_redirect_count;
`endif

InstructionDecoder U_InstructionDecoder (
    .opcode(ID_opcode),
    .Funct7(ID_Funct7),
    .Funct3(ID_Funct3),
    .rs1(ID_rs1),
    .rs2(ID_rs2),
    .rd(ID_rd),
    .dec_valid(dec_valid),
    .rfwrite(ID_RFWrite),
    .dmctrl(ID_DMCtrl),
    .alusrcb(ID_ALUSrcB),
    .wdsel(ID_WDSel),
    .aluop(ID_ALUOp)
);

assign ID_illegal = ID_valid && !dec_valid;

assign IF_stage_valid = IF_accept;
assign IF_stage_PC    = IM_PC;
// IM_PC is the address presented to the instruction master.  A redirect can
// make it differ from the registered PC for one cycle, so keep the accepted
// instruction's sequential PC derived from the same address.
NPC_prefix_adder32 U_IF_STAGE_PCA4_ADD (
    .A   (IM_PC),
    .B   (32'd4),
    .SUM (IF_stage_PCA4_sum)
);
assign IF_stage_PCA4 = IF_stage_PCA4_sum;

assign IF_accept             = InsMemRW && IF_ready;
assign IF_access_fault       = IF_accept && IF_error;
assign MEM_load_ready        = DM_ready && !DM_error;

ExceptionUnit U_ExceptionUnit (
    .clk(clk),
    .rst(rst),
    .id_valid(ID_valid),
    .id_pc(ID_PC),
    .id_ins(ID_ins),
    .id_illegal(ID_illegal),
    .id_access_fault(ID_access_fault),
    .ex_valid(EX_valid),
    .ex_branch(EX_branch),
    .ex_redirect_predicted(EX_redirect_predicted),
    .ex_pc(EX_PC),
    .ex_rfwrite(EX_RFWrite),
    .ex_wdsel(EX_WDSel),
    .ex_dmctrl(EX_DMCtrl),
    .ex_alu_result(ALU_result),
    .redirect_target(NPC),
    .mem_valid(MEM_valid),
    .mem_pc(MEM_PC),
    .mem_wdsel(MEM_WDSel),
    .mem_dmctrl(MEM_DMCtrl),
    .mem_address(ALU_result_r),
    .dm_ready(DM_ready),
    .dm_error(DM_error),
    .ex_exception(EX_exception),
    .mem_access_fault(MEM_access_fault),
    .mem_bus_wait(MEM_bus_wait),
    .trap_request(trap_request),
    .ex_redirect_wait(EX_redirect_wait),
    .ex_redirect(EX_redirect),
    .dm_req(DMReq),
    .trap(trap),
    .trap_cause(trap_cause),
    .trap_epc(trap_epc),
    .trap_tval(trap_tval)
);

/* ******************************** Outputs ******************************** */

always @(*) begin
    PCWrite         = IF_PCWrite && !trap && !trap_request &&
                      !MEM_bus_wait &&
                      (EX_redirect || ID_redirect ||
                       (!front_hazard_stall && IF_ready));
    InsMemRW        = IF_InsMemRW && !trap && !trap_request &&
                      !MEM_bus_wait && !front_hazard_stall;
    RFWrite         = WB_RFWrite;
    DMCtrl          = MEM_DMCtrl;
    ALUOp           = EX_ALUOp;
    NPCOp           = EX_NPCOp;

    mem_hold        = MEM_bus_wait || EX_redirect_wait;
    // A control transfer predicted in ID has already installed its target by
    // the time it reaches EX.  Only an actual EX redirect may select the EX
    // target again; otherwise advance the current fetch PC sequentially.
    PC_NPC          = ID_redirect ? ID_redirect_target :
                      EX_redirect ? NPC_NPC : PCA4;
    // Drive the EX-stage base PC directly so branch only acts as a final select,
    // not as a control input to the NPC adder cone.
    NPC_PC          = EX_PC;
    FETCH_PC        = IM_PC;
    NPC_EX_Offset20 = EX_Offset20;
    NPC_EX_Offset12 = EX_Offset;
    WB_rd_out       = WB_rd;
    forward1        = forward1_i;
    forward2        = forward2_i;
    FD1             = ID_RD1;
    FD2             = ID_RD2;
    EX_ALU_B        = EX_ALU_B_sel;
    RF_WD           = WB_WD;
    DM_WD           = MEM_WD;
    ID_rs1_out      = ID_rs1;
    ID_rs2_out      = ID_rs2;
end


/* ******************************** Pipeline Stages ******************************** */

/* ################################ IF ################################ */

assign NPC_NPC = NPC;

// decode
always @(*) begin
    IF_PCWrite  = 1'b1;
    IF_InsMemRW = 1'b1;
end

// Hazard detect in ID using only registered instruction fields.
// This keeps the raw IM output out of the fetch-address feedback loop.
assign pipe_flush = ID_redirect || EX_redirect || trap_request || trap;

HazardUnit U_HazardUnit (
    .id_valid(ID_valid),
    .id_opcode(ID_opcode),
    .id_rs1(ID_rs1),
    .id_rs2(ID_rs2),
    .ex_rd(EX_rd),
    .ex_valid(EX_valid),
    .ex_rfwrite(EX_RFWrite),
    .ex_wdsel(EX_WDSel),
    .mem_rd(MEM_rd),
    .mem_valid(MEM_valid),
    .mem_rfwrite(MEM_RFWrite),
    .mem_wdsel(MEM_WDSel),
    .mem_load_ready(MEM_load_ready),
    .pipe_flush(pipe_flush),
    .mem_bus_wait(MEM_bus_wait),
    .if_ready(IF_ready),
    .front_hazard_stall(front_hazard_stall),
    .if_stall(IF_stall)
);

assign IM_PC = EX_redirect ? NPC_NPC :
               ID_redirect ? ID_redirect_target : PC;



/* ################################ ID ################################ */

ForwardingUnit U_ForwardingUnit (
    .id_valid(ID_valid),
    .id_rs1(ID_rs1),
    .id_rs2(ID_rs2),
    .ex_rd(EX_rd),
    .ex_valid(EX_valid),
    .ex_rfwrite(EX_RFWrite),
    .ex_wdsel(EX_WDSel),
    .ex_pca4(EX_PCA4),
    .ex_alu_result(ALU_result),
    .mem_rd(MEM_rd),
    .mem_valid(MEM_valid),
    .mem_rfwrite(MEM_RFWrite),
    .mem_wdsel(MEM_WDSel),
    .mem_pca4(MEM_PCA4),
    .mem_alu_result(ALU_result_r),
    .mem_load_data(DM_RD),
    .mem_load_ready(MEM_load_ready),
    .wb_rd(WB_rd),
    .wb_valid(WB_valid),
    .wb_rfwrite(WB_RFWrite),
    .wb_data(WB_WD),
    .id_raw_rd1(RD1_raw),
    .id_raw_rd2(RD2_raw),
    .forward1(forward1_i),
    .forward2(forward2_i),
    .id_rd1(ID_RD1),
    .id_rd2(ID_RD2),
    .id_control_rd1(ID_control_RD1),
    .id_control_rd2(ID_control_RD2)
);

InstructionFields U_IDInstructionFields (
    .instruction(ID_ins),
    .opcode(ID_opcode), .funct7(ID_Funct7), .funct3(ID_Funct3),
    .rs1(ID_rs1), .rs2(ID_rs2), .rd(ID_rd),
    .imm12(ID_Imm12), .offset12(ID_Offset), .offset20(ID_Offset20)
);

IDRedirectUnit U_IDRedirectUnit (
    .id_valid(ID_valid),
    .opcode(ID_opcode), .funct3(ID_Funct3),
    .id_pc(ID_PC), .id_pca4(ID_PCA4),
    .imm12(ID_Imm12), .offset12(ID_Offset), .offset20(ID_Offset20),
    .control_rd1(ID_control_RD1), .control_rd2(ID_control_RD2),
    .front_hazard_stall(front_hazard_stall),
    .mem_bus_wait(MEM_bus_wait),
    .trap_request(trap_request), .trap(trap),
    .npcop(ID_NPCOp),
    .control_transfer(ID_control_transfer),
    .redirect(ID_redirect), .redirect_target(ID_redirect_target)
);

IDOperandSelector U_IDOperandSelector (
    .rd2(RD2),
    .imm12(ID_Imm12), .offset12(ID_Offset),
    .alusrcb(ID_ALUSrcB),
    .alu_b(ID_ALU_B_sel)
);

/* ################################ EX ################################ */

/* ################################ MEM ################################ */

/* ################################ WB ################################ */

assign MEM_writeback_data =
    (MEM_WDSel == `WDSel_FromMEM) ? DM_RD :
    (MEM_WDSel == `WDSel_FromPC)  ? MEM_PCA4 : ALU_result_r;


/* #################################### pipeline #################################### */

FetchDecodeRegisters U_FetchDecodeRegisters (
    .clk(clk), .rst(rst),
    .ready(!IF_stall), .kill(pipe_flush),
    .if_stage_pc(IF_stage_PC), .if_stage_pca4(IF_stage_PCA4),
    .if_stage_valid(IF_stage_valid),
    .raw_instruction(instruction),
    .if_access_fault(IF_access_fault),
    .id_pca4(ID_PCA4), .id_pc(ID_PC), .id_ins(ID_ins),
    .id_access_fault(ID_access_fault),
    .id_valid(ID_valid)
);

DecodeExecuteRegisters U_DecodeExecuteRegisters (
    .clk(clk), .rst(rst),
    .ready(!(MEM_bus_wait || EX_redirect_wait)),
    .kill(EX_redirect || trap_request || trap || IF_stall),
    .id_pca4(ID_PCA4), .id_pc(ID_PC),
    .id_alu_b(ID_ALU_B_sel), .id_offset(ID_Offset),
    .id_offset20(ID_Offset20), .id_rd(ID_rd),
    .id_aluop(ID_ALUOp), .id_wdsel(ID_WDSel),
    .id_rfwrite(ID_RFWrite),
    .id_dmctrl(ID_DMCtrl), .id_valid(ID_valid),
    .id_branch(ID_control_transfer),
    .id_redirect_predicted(ID_redirect), .id_npcop(ID_NPCOp),
    .ex_pca4(EX_PCA4), .ex_pc(EX_PC),
    .ex_alu_b(EX_ALU_B_sel), .ex_offset(EX_Offset),
    .ex_offset20(EX_Offset20), .ex_rd(EX_rd),
    .ex_aluop(EX_ALUOp), .ex_wdsel(EX_WDSel),
    .ex_rfwrite(EX_RFWrite),
    .ex_dmctrl(EX_DMCtrl), .ex_valid(EX_valid),
    .ex_branch(EX_branch),
    .ex_redirect_predicted(EX_redirect_predicted), .ex_npcop(EX_NPCOp)
);

// Kill only the faulting EX instruction. Older MEM/WB instructions may retire.
assign EX_to_MEM_kill = EX_exception || MEM_access_fault;

ExecuteMemoryRegisters U_ExecuteMemoryRegisters (
    .clk(clk), .rst(rst), .ready(!MEM_bus_wait),
    .kill(EX_redirect_wait || EX_to_MEM_kill),
    .ex_store_data(RD2_r), .ex_pca4(EX_PCA4), .ex_pc(EX_PC),
    .ex_rd(EX_rd), .ex_wdsel(EX_WDSel),
    .ex_rfwrite(EX_RFWrite), .ex_dmctrl(EX_DMCtrl),
    .ex_valid(EX_valid),
    .mem_store_data(MEM_WD), .mem_pca4(MEM_PCA4),
    .mem_pc(MEM_PC), .mem_rd(MEM_rd), .mem_wdsel(MEM_WDSel),
    .mem_rfwrite(MEM_RFWrite), .mem_dmctrl(MEM_DMCtrl),
    .mem_valid(MEM_valid)
);

MemoryWritebackRegisters U_MemoryWritebackRegisters (
    .clk(clk), .rst(rst),
    .ready(!MEM_bus_wait), .kill(MEM_access_fault),
    .mem_writeback_data(MEM_writeback_data),
    .mem_rd(MEM_rd),
    .mem_rfwrite(MEM_RFWrite), .mem_valid(MEM_valid),
    .wb_data(WB_WD), .wb_rd(WB_rd),
    .wb_rfwrite(WB_RFWrite), .wb_valid(WB_valid)
);

`ifdef DIFFTEST

always @(posedge clk or posedge rst) begin
    if (rst) begin
        perf_if_wait_cycles      <= 32'b0;
        perf_load_hazard_cycles <= 32'b0;
        perf_mem_wait_cycles     <= 32'b0;
        perf_redirect_count      <= 32'b0;
    end
    else if (!trap) begin
        if (MEM_bus_wait)
            perf_mem_wait_cycles <= perf_mem_wait_cycles + 32'd1;
        else if (front_hazard_stall)
            perf_load_hazard_cycles <= perf_load_hazard_cycles + 32'd1;
        else if (IF_InsMemRW && !IF_ready)
            perf_if_wait_cycles <= perf_if_wait_cycles + 32'd1;

        if (ID_redirect || EX_redirect)
            perf_redirect_count <= perf_redirect_count + 32'd1;
    end
end

export "DPI-C" function DPI_getIfWaitCycles;
function int DPI_getIfWaitCycles();
    return perf_if_wait_cycles;
endfunction

export "DPI-C" function DPI_getLoadHazardCycles;
function int DPI_getLoadHazardCycles();
    return perf_load_hazard_cycles;
endfunction

export "DPI-C" function DPI_getMemWaitCycles;
function int DPI_getMemWaitCycles();
    return perf_mem_wait_cycles;
endfunction

export "DPI-C" function DPI_getRedirectCount;
function int DPI_getRedirectCount();
    return perf_redirect_count;
endfunction

reg [31:0] ID_dnpc, EX_dnpc, MEM_dnpc, WB_dnpc, dnpc;

always @(posedge clk or posedge rst) begin
    if (rst) begin
        ID_dnpc       <= 32'b0;
        EX_dnpc       <= 32'b0;
        MEM_dnpc      <= 32'b0;
        WB_dnpc       <= 32'b0;
        dnpc          <= 32'b0;
    end
    else begin
        if (pipe_flush)
            ID_dnpc <= 32'b0;
        else if (!IF_stall)
            ID_dnpc <= IF_stage_PCA4;

        if (!(MEM_bus_wait || EX_redirect_wait)) begin
            if (pipe_flush || IF_stall)
                EX_dnpc <= 32'b0;
            else
                EX_dnpc <= ID_dnpc;
        end

        if (!MEM_bus_wait) begin
            if (EX_redirect_wait || EX_to_MEM_kill)
                MEM_dnpc <= 32'b0;
            else
                MEM_dnpc <= EX_branch ? NPC_NPC : EX_dnpc;
        end

        if (MEM_bus_wait || MEM_access_fault)
            WB_dnpc <= 32'b0;
        else
            WB_dnpc <= MEM_dnpc;

        dnpc <= WB_dnpc;
    end
end

export "DPI-C" function DPI_getPC;
function int DPI_getPC();
    return dnpc;
endfunction

`endif


endmodule

// Source: rtl/rtl/DM.v
module DM(clk, addr, write_data, write_enable, read_data);
    input         clk;
    input  [11:2] addr;
    input  [31:0] write_data;
    input         write_enable;
    output reg [31:0] read_data;

`ifndef SRAM

    reg [31:0] memory[0:1023];

    always @(posedge clk) begin
        if (write_enable) begin
            memory[addr] <= write_data;
        end
        else begin
            read_data <= memory[addr];
        end
    end

`endif

`ifdef SRAM

    wire [63:0] sram_out;

    TS1N65LPLL2048X64M8 memory (
        .CLK(clk),
        .CEB(1'b0),
        .WEB(~write_enable),
        .A({1'b0, addr}),
        .D({32'b0, write_data}),
        .BWEB(64'b0),
        .Q(sram_out),
        .TSEL(2'b01)
    );

    always @(*) read_data = sram_out[31:0];

`endif

endmodule

// Source: rtl/rtl/ExceptionUnit.v
module ExceptionUnit(
    input         clk,
    input         rst,
    input         id_valid,
    input  [31:0] id_pc,
    input  [31:0] id_ins,
    input         id_illegal,
    input         id_access_fault,
    input         ex_valid,
    input         ex_branch,
    input         ex_redirect_predicted,
    input  [31:0] ex_pc,
    input         ex_rfwrite,
    input  [1:0]  ex_wdsel,
    input         ex_dmctrl,
    input  [31:0] ex_alu_result,
    input  [31:0] redirect_target,
    input         mem_valid,
    input  [31:0] mem_pc,
    input  [1:0]  mem_wdsel,
    input         mem_dmctrl,
    input  [31:0] mem_address,
    input         dm_ready,
    input         dm_error,

    output ex_exception,
    output mem_access_fault,
    output mem_bus_wait,
    output trap_request,
    output ex_redirect_wait,
    output ex_redirect,
    output dm_req,
    output reg        trap,
    output reg [3:0]  trap_cause,
    output reg [31:0] trap_epc,
    output reg [31:0] trap_tval
);

reg [3:0]  trap_cause_next;
reg [31:0] trap_epc_next;
reg [31:0] trap_tval_next;
wire id_inst_misaligned;
wire id_illegal_exception;
wire id_breakpoint_exception;
wire ex_ctrl_misaligned;
wire ex_load_misaligned;
wire ex_store_misaligned;
wire mem_load_access_fault;
wire mem_store_access_fault;

// The core implements IALIGN=32 and only word-sized data accesses.
assign id_inst_misaligned = id_valid && (id_pc[1:0] != 2'b00);
`ifdef DIFFTEST
assign id_breakpoint_exception = 1'b0;
`else
assign id_breakpoint_exception = id_valid && (id_ins == 32'h0010_0073);
`endif
assign id_illegal_exception = id_valid && id_illegal &&
                              !id_breakpoint_exception;

assign ex_ctrl_misaligned = ex_valid && ex_branch &&
                            (redirect_target[1:0] != 2'b00);
assign ex_load_misaligned = ex_valid && ex_rfwrite &&
                            (ex_wdsel == `WDSel_FromMEM) &&
                            (ex_alu_result[1:0] != 2'b00);
assign ex_store_misaligned = ex_valid && (ex_dmctrl == `DMCtrl_WR) &&
                             (ex_alu_result[1:0] != 2'b00);
assign ex_exception = ex_ctrl_misaligned || ex_load_misaligned ||
                      ex_store_misaligned;

assign dm_req = mem_valid && ((mem_wdsel == `WDSel_FromMEM) ||
                             (mem_dmctrl == `DMCtrl_WR));
assign mem_load_access_fault = dm_req && dm_ready && dm_error &&
                               (mem_wdsel == `WDSel_FromMEM);
assign mem_store_access_fault = dm_req && dm_ready && dm_error &&
                                (mem_dmctrl == `DMCtrl_WR);
assign mem_access_fault = mem_load_access_fault || mem_store_access_fault;
assign mem_bus_wait = dm_req && !dm_ready;

// MEM faults are oldest. Younger exceptions and redirects wait behind a
// pending memory operation so the reported exception remains precise.
assign trap_request = !trap &&
                      (mem_access_fault ||
                       (!mem_bus_wait &&
                        (ex_exception ||
                         (!ex_branch &&
                          (id_access_fault || id_inst_misaligned ||
                           id_illegal_exception ||
                           id_breakpoint_exception)))));
// The instruction master can start a target request in the redirect cycle. It
// does not need to wait for a previous external instruction-bus response.
assign ex_redirect_wait = 1'b0;
assign ex_redirect = ex_branch && !ex_redirect_predicted &&
                     !ex_ctrl_misaligned &&
                     !mem_bus_wait && !mem_access_fault && !trap;

always @(*) begin
    trap_cause_next = `TRAP_ILLEGAL_INSTRUCTION;
    trap_epc_next   = id_pc;
    trap_tval_next  = id_ins;

    if (mem_load_access_fault) begin
        trap_cause_next = `TRAP_LOAD_ACCESS_FAULT;
        trap_epc_next   = mem_pc;
        trap_tval_next  = mem_address;
    end
    else if (mem_store_access_fault) begin
        trap_cause_next = `TRAP_STORE_ACCESS_FAULT;
        trap_epc_next   = mem_pc;
        trap_tval_next  = mem_address;
    end
    else if (ex_ctrl_misaligned) begin
        trap_cause_next = `TRAP_INST_ADDR_MISALIGNED;
        trap_epc_next   = ex_pc;
        trap_tval_next  = redirect_target;
    end
    else if (ex_load_misaligned) begin
        trap_cause_next = `TRAP_LOAD_ADDR_MISALIGNED;
        trap_epc_next   = ex_pc;
        trap_tval_next  = ex_alu_result;
    end
    else if (ex_store_misaligned) begin
        trap_cause_next = `TRAP_STORE_ADDR_MISALIGNED;
        trap_epc_next   = ex_pc;
        trap_tval_next  = ex_alu_result;
    end
    else if (id_access_fault) begin
        trap_cause_next = `TRAP_INST_ACCESS_FAULT;
        trap_epc_next   = id_pc;
        trap_tval_next  = id_pc;
    end
    else if (id_inst_misaligned) begin
        trap_cause_next = `TRAP_INST_ADDR_MISALIGNED;
        trap_epc_next   = id_pc;
        trap_tval_next  = id_pc;
    end
    else if (id_breakpoint_exception) begin
        trap_cause_next = `TRAP_BREAKPOINT;
        trap_epc_next   = id_pc;
        trap_tval_next  = id_pc;
    end
end

always @(posedge clk or posedge rst) begin
    if (rst) begin
        trap       <= 1'b0;
        trap_cause <= 4'b0;
        trap_epc   <= 32'b0;
        trap_tval  <= 32'b0;
    end
    else if (trap_request) begin
        trap       <= 1'b1;
        trap_cause <= trap_cause_next;
        trap_epc   <= trap_epc_next;
        trap_tval  <= trap_tval_next;
    end
end

endmodule

// Source: rtl/rtl/Flopr.v
module Flopr #(parameter WIDTH = 32)(clk, rst, in_data, out_data);
    input         clk;
    input         rst;
    input  [WIDTH-1:0] in_data;
    output reg [WIDTH-1:0] out_data;

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            out_data <= {WIDTH{1'b0}};
        end
        else begin
            out_data <= in_data;
        end
    end

endmodule

// Source: rtl/rtl/ForwardingUnit.v
module ForwardingUnit(
    input         id_valid,
    input  [4:0]  id_rs1,
    input  [4:0]  id_rs2,
    input  [4:0]  ex_rd,
    input         ex_valid,
    input         ex_rfwrite,
    input  [1:0]  ex_wdsel,
    input  [31:0] ex_pca4,
    input  [31:0] ex_alu_result,
    input  [4:0]  mem_rd,
    input         mem_valid,
    input         mem_rfwrite,
    input  [1:0]  mem_wdsel,
    input  [31:0] mem_pca4,
    input  [31:0] mem_alu_result,
    input  [31:0] mem_load_data,
    input         mem_load_ready,
    input  [4:0]  wb_rd,
    input         wb_valid,
    input         wb_rfwrite,
    input  [31:0] wb_data,
    input  [31:0] id_raw_rd1,
    input  [31:0] id_raw_rd2,

    output        forward1,
    output        forward2,
    output [31:0] id_rd1,
    output [31:0] id_rd2,
    output [31:0] id_control_rd1,
    output [31:0] id_control_rd2
);

wire wb_forward1;
wire wb_forward2;
wire mem_forward1;
wire mem_forward2;
wire mem_control_forward1;
wire mem_control_forward2;
wire ex_forward1;
wire ex_forward2;
wire [31:0] ex_forward_data;
wire [31:0] mem_forward_data;
wire [31:0] mem_control_forward_data;

assign wb_forward1 = id_valid && wb_valid && (id_rs1 == wb_rd) &&
                     wb_rfwrite && (wb_rd != 5'b0);
assign wb_forward2 = id_valid && wb_valid && (id_rs2 == wb_rd) &&
                     wb_rfwrite && (wb_rd != 5'b0);

assign ex_forward1 = id_valid && ex_valid && (id_rs1 == ex_rd) && ex_rfwrite &&
                     (ex_wdsel != `WDSel_FromMEM) && (ex_rd != 5'b0);
assign ex_forward2 = id_valid && ex_valid && (id_rs2 == ex_rd) && ex_rfwrite &&
                     (ex_wdsel != `WDSel_FromMEM) && (ex_rd != 5'b0);
assign mem_forward1 = id_valid && mem_valid && (id_rs1 == mem_rd) && mem_rfwrite &&
                      ((mem_wdsel != `WDSel_FromMEM) || mem_load_ready) &&
                      (mem_rd != 5'b0);
assign mem_forward2 = id_valid && mem_valid && (id_rs2 == mem_rd) && mem_rfwrite &&
                      ((mem_wdsel != `WDSel_FromMEM) || mem_load_ready) &&
                      (mem_rd != 5'b0);
assign mem_control_forward1 = id_valid && mem_valid &&
                              (id_rs1 == mem_rd) && mem_rfwrite &&
                              (mem_wdsel != `WDSel_FromMEM) &&
                              (mem_rd != 5'b0);
assign mem_control_forward2 = id_valid && mem_valid &&
                              (id_rs2 == mem_rd) && mem_rfwrite &&
                              (mem_wdsel != `WDSel_FromMEM) &&
                              (mem_rd != 5'b0);

assign ex_forward_data = (ex_wdsel == `WDSel_FromPC) ?
                         ex_pca4 : ex_alu_result;
assign mem_forward_data = (mem_wdsel == `WDSel_FromMEM) ? mem_load_data :
                          (mem_wdsel == `WDSel_FromPC) ? mem_pca4 :
                          mem_alu_result;
// Control transfers wait for loads to reach WB.  Keeping DM load data out of
// this data mux physically cuts the data-SRAM-to-fetch-address timing path.
assign mem_control_forward_data = (mem_wdsel == `WDSel_FromPC) ?
                                  mem_pca4 : mem_alu_result;

assign forward1 = ex_forward1 || mem_forward1 || wb_forward1;
assign forward2 = ex_forward2 || mem_forward2 || wb_forward2;

// The youngest producer wins: EX, then MEM, then WB.
assign id_rd1 = ex_forward1 ? ex_forward_data :
                mem_forward1 ? mem_forward_data :
                wb_forward1 ? wb_data : 32'h0;
assign id_rd2 = ex_forward2 ? ex_forward_data :
                mem_forward2 ? mem_forward_data :
                wb_forward2 ? wb_data : 32'h0;

assign id_control_rd1 = ex_forward1 ? ex_forward_data :
                        mem_control_forward1 ? mem_control_forward_data :
                        wb_forward1 ? wb_data : id_raw_rd1;
assign id_control_rd2 = ex_forward2 ? ex_forward_data :
                        mem_control_forward2 ? mem_control_forward_data :
                        wb_forward2 ? wb_data : id_raw_rd2;

endmodule

// Source: rtl/rtl/HazardUnit.v
module HazardUnit(
    input        id_valid,
    input  [6:0] id_opcode,
    input  [4:0] id_rs1,
    input  [4:0] id_rs2,
    input  [4:0] ex_rd,
    input        ex_valid,
    input        ex_rfwrite,
    input  [1:0] ex_wdsel,
    input  [4:0] mem_rd,
    input        mem_valid,
    input        mem_rfwrite,
    input  [1:0] mem_wdsel,
    input        mem_load_ready,
    input        pipe_flush,
    input        mem_bus_wait,
    input        if_ready,

    output front_hazard_stall,
    output if_stall
);

wire id_use_rs1;
wire id_use_rs2;
wire id_control_transfer;
wire id_dep_ex;
wire id_dep_mem;

assign id_use_rs1 = (id_opcode == `INSTR_RTYPE_OP) ||
                    (id_opcode == `INSTR_ITYPE_OP) ||
                    (id_opcode == `INSTR_LW_OP)    ||
                    (id_opcode == `INSTR_SW_OP)    ||
                    (id_opcode == `INSTR_BTYPE_OP) ||
                    (id_opcode == `INSTR_JALR_OP);
assign id_use_rs2 = (id_opcode == `INSTR_RTYPE_OP) ||
                    (id_opcode == `INSTR_SW_OP)    ||
                    (id_opcode == `INSTR_BTYPE_OP);
assign id_control_transfer = (id_opcode == `INSTR_BTYPE_OP) ||
                             (id_opcode == `INSTR_JALR_OP);

assign id_dep_ex = id_valid && ex_valid &&
                   (((id_use_rs1 && (id_rs1 == ex_rd)) ||
                     (id_use_rs2 && (id_rs2 == ex_rd))) &&
                    ex_rfwrite && (ex_wdsel == `WDSel_FromMEM) &&
                    (ex_rd != 5'b0));
assign id_dep_mem = id_valid && mem_valid &&
                    (((id_use_rs1 && (id_rs1 == mem_rd)) ||
                     (id_use_rs2 && (id_rs2 == mem_rd))) &&
                     mem_rfwrite && (mem_wdsel == `WDSel_FromMEM) &&
                     (!mem_load_ready || id_control_transfer) &&
                     (mem_rd != 5'b0));
assign front_hazard_stall = id_dep_ex || id_dep_mem;
assign if_stall = !pipe_flush &&
                  (mem_bus_wait || front_hazard_stall || !if_ready);

endmodule

// Source: rtl/rtl/IDOperandSelector.v
// ID-stage ALU B operand extension and selection.
module IDOperandSelector(
    input  [31:0] rd2,
    input  [11:0] imm12,
    input  [11:0] offset12,
    input  [1:0]  alusrcb,
    output reg [31:0] alu_b
);

wire [31:0] imm32;
wire [31:0] offset32;

assign imm32 = {{20{imm12[11]}}, imm12};
assign offset32 = {{20{offset12[11]}}, offset12};

always @(*) begin
    case (alusrcb)
        `ALUSrcB_B     : alu_b = rd2;
        `ALUSrcB_Imm   : alu_b = imm32;
        `ALUSrcB_Offset: alu_b = offset32;
        default        : alu_b = rd2;
    endcase
end

endmodule

// Source: rtl/rtl/IDRedirectUnit.v
// ID-stage control-transfer decision and redirect target generation.
module IDRedirectUnit(
    input         id_valid,
    input  [6:0]  opcode,
    input  [2:0]  funct3,
    input  [31:0] id_pc,
    input  [31:0] id_pca4,
    input  [11:0] imm12,
    input  [11:0] offset12,
    input  [19:0] offset20,
    input  [31:0] control_rd1,
    input  [31:0] control_rd2,
    input         front_hazard_stall,
    input         mem_bus_wait,
    input         trap_request,
    input         trap,

    output reg [1:0]  npcop,
    output            control_transfer,
    output            redirect,
    output reg [31:0] redirect_target
);

wire operands_equal;
wire is_beq;
wire is_bne;
wire take_branch;
wire [31:0] branch_target;
wire [31:0] jal_target;
wire [31:0] jalr_target_sum;

assign operands_equal = (control_rd1 == control_rd2);
assign is_beq = (opcode == `INSTR_BTYPE_OP) &&
                (funct3 == `INSTR_BEQ_FUNCT);
assign is_bne = (opcode == `INSTR_BTYPE_OP) &&
                (funct3 == `INSTR_BNE_FUNCT);
assign take_branch = (is_beq && operands_equal) ||
                     (is_bne && !operands_equal);

always @(*) begin
    npcop = `NPC_PC;
    if (take_branch) begin
        npcop = `NPC_Offset12;
    end
    else if (opcode == `INSTR_JAL_OP) begin
        npcop = `NPC_Offset20;
    end
    else if (opcode == `INSTR_JALR_OP) begin
        npcop = `NPC_rs;
    end
end

// Keep the target adders independent so no operand mux is inserted ahead of
// the carry network on the fetch-address path.
NPC_prefix_adder32 U_BRANCH_TARGET_ADD (
    .A   (id_pc),
    .B   ({{19{offset12[11]}}, offset12, 1'b0}),
    .SUM (branch_target)
);

NPC_prefix_adder32 U_JAL_TARGET_ADD (
    .A   (id_pc),
    .B   ({{11{offset20[19]}}, offset20, 1'b0}),
    .SUM (jal_target)
);

NPC_prefix_adder32 U_JALR_TARGET_ADD (
    .A   (control_rd1),
    .B   ({{20{imm12[11]}}, imm12}),
    .SUM (jalr_target_sum)
);

always @(*) begin
    case (npcop)
        `NPC_Offset12: redirect_target = branch_target;
        `NPC_Offset20: redirect_target = jal_target;
        `NPC_rs:       redirect_target = jalr_target_sum & 32'hffff_fffe;
        default:       redirect_target = id_pca4;
    endcase
end

assign control_transfer = (npcop != `NPC_PC);
assign redirect = id_valid && control_transfer &&
                  (redirect_target[1:0] == 2'b00) &&
                  !front_hazard_stall && !mem_bus_wait &&
                  !trap_request && !trap;

endmodule

// Source: rtl/rtl/IM.v
module IM(clk, rst, enable, addr, data);
    input           clk;
    input           rst;
    input           enable;
    input   [8:0]   addr;
    output reg [63:0] data;

`ifndef SRAM

    `ifndef DIFFTEST
    `ifndef SYNTHESIS
    reg [31:0] memory[0:1023];
    `endif
    `endif

    `ifdef DIFFTEST
    import "DPI-C" function longint unsigned instructionBusRead(input int addr);
    `endif

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            data <= 64'b0;
        end
        else begin
            `ifdef DIFFTEST
            data <= enable ? instructionBusRead({20'h00002, addr, 3'b000}) : data;
            `endif

            `ifndef DIFFTEST
            `ifndef SYNTHESIS
            data <= enable ? {memory[{addr, 1'b1}], memory[{addr, 1'b0}]} : data;
            `endif
            `endif
        end
    end

`endif

`ifdef SRAM

    wire [63:0] sram_out;

    TS1N65LPLL2048X64M8 memory (
        .CLK(clk),
        .CEB(~enable),
        .WEB(1'b1),
        .A({2'b00, addr}),
        .D(64'b0),
        .BWEB(64'b0),
        .Q(sram_out),
        .TSEL(2'b01)
    );

    always @(*) data = sram_out;

`endif


endmodule

// Source: rtl/rtl/InstructionFields.v
// Structural instruction-field extraction for the registered ID instruction.
module InstructionFields(
    input  [31:0] instruction,
    output [6:0]  opcode,
    output [6:0]  funct7,
    output [2:0]  funct3,
    output [4:0]  rs1,
    output [4:0]  rs2,
    output [4:0]  rd,
    output [11:0] imm12,
    output [11:0] offset12,
    output [19:0] offset20
);

assign opcode = instruction[6:0];
assign funct7 = instruction[31:25];
assign funct3 = instruction[14:12];
assign rs1 = instruction[19:15];
assign rs2 = instruction[24:20];
assign rd = instruction[11:7];
assign imm12 = instruction[31:20];
assign offset20 = {instruction[31], instruction[19:12], instruction[20],
                   instruction[30:21]};
assign offset12 = (opcode == `INSTR_BTYPE_OP) ?
                  {instruction[31], instruction[7], instruction[30:25],
                   instruction[11:8]} :
                  (opcode == `INSTR_SW_OP) ?
                  {instruction[31:25], instruction[11:7]} : imm12;

endmodule

// Source: rtl/rtl/InstructionDecoder.v
module InstructionDecoder(
    input  [6:0] opcode,
    input  [6:0] Funct7,
    input  [2:0] Funct3,
    input  [4:0] rs1,
    input  [4:0] rs2,
    input  [4:0] rd,

    output dec_valid,

    output       rfwrite,
    output       dmctrl,
    output [1:0] alusrcb,
    output [1:0] wdsel,
    output [3:0] aluop
);

wire dec_is_rtype;
wire dec_is_itype;
wire dec_is_lw;
wire dec_is_sw;
wire dec_is_btype;
wire dec_is_jal;
wire dec_is_jalr;
wire dec_r_add;
wire dec_r_sub;
wire dec_r_and;
wire dec_r_or;
wire dec_r_xor;
wire dec_r_sll;
wire dec_r_srl;
wire dec_r_sra;
wire dec_r_valid;
wire dec_i_addi;
wire dec_i_ori;
wire dec_i_valid;
wire dec_lw_valid;
wire dec_sw_valid;
wire dec_b_valid;
wire dec_jal_valid;
wire dec_jalr_valid;
`ifdef DIFFTEST
wire dec_is_ebreak;
`endif

assign dec_is_rtype = (opcode == `INSTR_RTYPE_OP);
assign dec_is_itype = (opcode == `INSTR_ITYPE_OP);
assign dec_is_lw    = (opcode == `INSTR_LW_OP);
assign dec_is_sw    = (opcode == `INSTR_SW_OP);
assign dec_is_btype = (opcode == `INSTR_BTYPE_OP);
assign dec_is_jal   = (opcode == `INSTR_JAL_OP);
assign dec_is_jalr  = (opcode == `INSTR_JALR_OP);

assign dec_r_add = dec_is_rtype && ({Funct7, Funct3} == `INSTR_ADD_FUNCT);
assign dec_r_sub = dec_is_rtype && ({Funct7, Funct3} == `INSTR_SUB_FUNCT);
assign dec_r_and = dec_is_rtype && ({Funct7, Funct3} == `INSTR_AND_FUNCT);
assign dec_r_or  = dec_is_rtype && ({Funct7, Funct3} == `INSTR_OR_FUNCT);
assign dec_r_xor = dec_is_rtype && ({Funct7, Funct3} == `INSTR_XOR_FUNCT);
assign dec_r_sll = dec_is_rtype && ({Funct7, Funct3} == `INSTR_SLL_FUNCT);
assign dec_r_srl = dec_is_rtype && ({Funct7, Funct3} == `INSTR_SRL_FUNCT);
assign dec_r_sra = dec_is_rtype && ({Funct7, Funct3} == `INSTR_SRA_FUNCT);
assign dec_r_valid = dec_r_add || dec_r_sub || dec_r_and || dec_r_or ||
                     dec_r_xor || dec_r_sll || dec_r_srl || dec_r_sra;

assign dec_i_addi  = dec_is_itype && (Funct3 == `INSTR_ADDI_FUNCT);
assign dec_i_ori   = dec_is_itype && (Funct3 == `INSTR_ORI_FUNCT);
assign dec_i_valid = dec_i_addi || dec_i_ori;

assign dec_lw_valid   = dec_is_lw    && (Funct3 == 3'b010);
assign dec_sw_valid   = dec_is_sw    && (Funct3 == 3'b010);
assign dec_b_valid    = dec_is_btype && ((Funct3 == `INSTR_BEQ_FUNCT) ||
                                         (Funct3 == `INSTR_BNE_FUNCT));
assign dec_jal_valid  = dec_is_jal;
assign dec_jalr_valid = dec_is_jalr && (Funct3 == 3'b000);
`ifdef DIFFTEST
assign dec_is_ebreak  = ({Funct7, rs2, rs1, Funct3, rd, opcode} ==
                         32'h0010_0073);
`endif

assign dec_valid = dec_r_valid || dec_i_valid || dec_lw_valid ||
                   dec_sw_valid || dec_b_valid || dec_jal_valid ||
                   dec_jalr_valid
`ifdef DIFFTEST
                   || dec_is_ebreak
`endif
                   ;

assign rfwrite = dec_r_valid || dec_i_valid || dec_lw_valid ||
                 dec_jal_valid || dec_jalr_valid;
assign dmctrl = dec_sw_valid ? `DMCtrl_WR : `DMCtrl_RD;
assign alusrcb = (dec_i_valid || dec_jalr_valid) ? `ALUSrcB_Imm :
                 ((dec_lw_valid || dec_sw_valid) ?
                  `ALUSrcB_Offset : `ALUSrcB_B);
assign wdsel = dec_lw_valid ? `WDSel_FromMEM :
               ((dec_jal_valid || dec_jalr_valid) ?
                `WDSel_FromPC : `WDSel_FromALU);

// ALU control does not need the full legal-instruction reduction. Illegal
// instructions are qualified by dec_valid before they can change state. This
// keeps unrelated Funct7 bits out of the ID-to-EX ALU-control path.
assign aluop[0] = dec_is_btype || dec_i_ori ||
                  (dec_is_rtype &&
                   (((Funct3 == 3'b000) && Funct7[5]) ||
                    (Funct3 == 3'b110) || (Funct3 == 3'b101)));
assign aluop[1] = dec_i_ori ||
                  (dec_is_rtype &&
                   ((Funct3 == 3'b111) || (Funct3 == 3'b110)));
assign aluop[2] = dec_is_rtype && Funct3[2] && !Funct3[1] &&
                  (!Funct3[0] || Funct7[5]);
assign aluop[3] = dec_is_rtype && !Funct3[1] && Funct3[0] &&
                  (!Funct3[2] || !Funct7[5]);

endmodule

// Source: rtl/rtl/NPC.v
module NPC(NPCOp, PC, PCA4, NPC, NPC_PC, NPC_Offset12, NPC_Offset20, NPC_rs, NPC_taken_p4);
    input  [1:0]  NPCOp;
    input  [31:0] PC;
    output reg [31:0] PCA4;
    output reg [31:0] NPC;
    output reg [31:0] NPC_taken_p4;

    input [31:0] NPC_PC;
    input [12:1] NPC_Offset12;
    input [20:1] NPC_Offset20;
    input [31:0] NPC_rs;

wire signed [12:0] Offset13;
wire signed [20:0] Offset21;
wire signed [31:0] Imm12Ext;
wire signed [31:0] Imm12ExtP4;
wire signed [31:0] Offset12ShiftExt;
wire signed [31:0] Offset20ShiftExt;
wire signed [31:0] Offset12ShiftExtP4;
wire signed [31:0] Offset20ShiftExtP4;
wire [31:0] jalr_target;
wire [31:0] jalr_target_p4;
wire signed [31:0] npc_offset12_taken;
wire signed [31:0] npc_offset20_taken;
wire signed [31:0] npc_offset12_taken_p4;
wire signed [31:0] npc_offset20_taken_p4;
wire [31:0] seq_pc_plus4;
wire [31:0] ex_pc_plus8;
wire [31:0] jalr_sum;
wire [31:0] jalr_sum_p4;
wire [31:0] seq_pc_plus4_sum;
wire [31:0] ex_pc_plus8_sum;
wire [31:0] npc_offset12_taken_sum;
wire [31:0] npc_offset20_taken_sum;
wire [31:0] npc_offset12_taken_p4_sum;
wire [31:0] npc_offset20_taken_p4_sum;
wire [31:0] imm12_ext_p4_sum;
wire [31:0] offset12_shift_ext_p4_sum;
wire [31:0] offset20_shift_ext_p4_sum;

assign Offset13 = $signed({NPC_Offset12[12:1], 1'b0});
assign Offset21 = $signed({NPC_Offset20[20:1], 1'b0});
assign Imm12Ext = {{20{NPC_Offset12[12]}}, NPC_Offset12[12:1]};
assign Offset12ShiftExt = {{19{Offset13[12]}}, Offset13};
assign Offset20ShiftExt = {{11{Offset21[20]}}, Offset21};
// Keep the +4 candidates out of inferred '+' logic.  These values feed the
// branch/JALR target-plus-4 calculations, so a ripple adder here would sit in
// series with the target adder on the PC critical path.
NPC_prefix_adder32 U_NPC_IMM12_PLUS4 (
    .A   (Imm12Ext),
    .B   (32'd4),
    .SUM (imm12_ext_p4_sum)
);
NPC_prefix_adder32 U_NPC_OFFSET12_PLUS4 (
    .A   (Offset12ShiftExt),
    .B   (32'd4),
    .SUM (offset12_shift_ext_p4_sum)
);
NPC_prefix_adder32 U_NPC_OFFSET20_PLUS4 (
    .A   (Offset20ShiftExt),
    .B   (32'd4),
    .SUM (offset20_shift_ext_p4_sum)
);
assign Imm12ExtP4 = $signed(imm12_ext_p4_sum);
assign Offset12ShiftExtP4 = $signed(offset12_shift_ext_p4_sum);
assign Offset20ShiftExtP4 = $signed(offset20_shift_ext_p4_sum);

NPC_prefix_adder32 U_NPC_SEQ_PC_PLUS4 (
    .A   (PC),
    .B   (32'd4),
    .SUM (seq_pc_plus4_sum)
);
NPC_prefix_adder32 U_NPC_EX_PC_PLUS8 (
    .A   (NPC_PC),
    .B   (32'd8),
    .SUM (ex_pc_plus8_sum)
);
NPC_prefix_adder32 U_NPC_OFFSET12_TAKEN (
    .A   (NPC_PC),
    .B   (Offset12ShiftExt),
    .SUM (npc_offset12_taken_sum)
);
NPC_prefix_adder32 U_NPC_OFFSET20_TAKEN (
    .A   (NPC_PC),
    .B   (Offset20ShiftExt),
    .SUM (npc_offset20_taken_sum)
);
NPC_prefix_adder32 U_NPC_OFFSET12_TAKEN_P4 (
    .A   (NPC_PC),
    .B   (Offset12ShiftExtP4),
    .SUM (npc_offset12_taken_p4_sum)
);
NPC_prefix_adder32 U_NPC_OFFSET20_TAKEN_P4 (
    .A   (NPC_PC),
    .B   (Offset20ShiftExtP4),
    .SUM (npc_offset20_taken_p4_sum)
);
NPC_prefix_adder32 U_JALR_ADD (
    .A   (NPC_rs),
    .B   (Imm12Ext),
    .SUM (jalr_sum)
);
NPC_prefix_adder32 U_JALR_ADD_P4 (
    .A   (NPC_rs),
    .B   (Imm12ExtP4),
    .SUM (jalr_sum_p4)
);
assign jalr_target = jalr_sum & 32'hffff_fffe;
assign jalr_target_p4 = jalr_sum_p4 & 32'hffff_fffe;
assign seq_pc_plus4 = seq_pc_plus4_sum;
assign ex_pc_plus8 = ex_pc_plus8_sum;
assign npc_offset12_taken = $signed(npc_offset12_taken_sum);
assign npc_offset20_taken = $signed(npc_offset20_taken_sum);
assign npc_offset12_taken_p4 = $signed(npc_offset12_taken_p4_sum);
assign npc_offset20_taken_p4 = $signed(npc_offset20_taken_p4_sum);

always @(*) begin
    case(NPCOp)
        `NPC_PC       : NPC = seq_pc_plus4;
        `NPC_Offset12 : NPC = npc_offset12_taken;
        `NPC_rs       : NPC = NPC_rs;
        `NPC_Offset20 : NPC = npc_offset20_taken;
        default       : NPC = seq_pc_plus4;
    endcase

    // Added logic only: keep original case items unchanged, then refine jalr target.
    if (NPCOp == `NPC_rs) begin
        NPC = jalr_target;
    end

    case (NPCOp)
        `NPC_Offset12 : NPC_taken_p4 = npc_offset12_taken_p4;
        `NPC_Offset20 : NPC_taken_p4 = npc_offset20_taken_p4;
        `NPC_rs       : NPC_taken_p4 = jalr_target_p4;
        `NPC_PC       : NPC_taken_p4 = ex_pc_plus8;
        default       : NPC_taken_p4 = seq_pc_plus4;
    endcase

    PCA4 = seq_pc_plus4;
end


endmodule

// 32-bit Kogge-Stone-style prefix adder.  The five prefix stages replace the
// long bit-by-bit carry propagation inferred from a plain 32-bit '+' operator.
module NPC_prefix_adder32(A, B, SUM);
    input  [31:0] A;
    input  [31:0] B;
    output [31:0] SUM;

    wire [31:0] p0;
    wire [31:0] g0;
    wire [31:0] p1, g1;
    wire [31:0] p2, g2;
    wire [31:0] p3, g3;
    wire [31:0] p4, g4;
    wire [31:0] p5, g5;
    wire [31:0] carry;

    assign p0 = A ^ B;
    assign g0 = A & B;

    genvar i;
    generate
        for (i = 0; i < 32; i = i + 1) begin : GEN_PREFIX
            if (i < 1) begin
                assign p1[i] = p0[i];
                assign g1[i] = g0[i];
            end else begin
                assign p1[i] = p0[i] & p0[i-1];
                assign g1[i] = g0[i] | (p0[i] & g0[i-1]);
            end

            if (i < 2) begin
                assign p2[i] = p1[i];
                assign g2[i] = g1[i];
            end else begin
                assign p2[i] = p1[i] & p1[i-2];
                assign g2[i] = g1[i] | (p1[i] & g1[i-2]);
            end

            if (i < 4) begin
                assign p3[i] = p2[i];
                assign g3[i] = g2[i];
            end else begin
                assign p3[i] = p2[i] & p2[i-4];
                assign g3[i] = g2[i] | (p2[i] & g2[i-4]);
            end

            if (i < 8) begin
                assign p4[i] = p3[i];
                assign g4[i] = g3[i];
            end else begin
                assign p4[i] = p3[i] & p3[i-8];
                assign g4[i] = g3[i] | (p3[i] & g3[i-8]);
            end

            if (i < 16) begin
                assign p5[i] = p4[i];
                assign g5[i] = g4[i];
            end else begin
                assign p5[i] = p4[i] & p4[i-16];
                assign g5[i] = g4[i] | (p4[i] & g4[i-16]);
            end
        end

        for (i = 0; i < 32; i = i + 1) begin : GEN_SUM
            if (i == 0) begin
                assign carry[i] = 1'b0;
            end else begin
                assign carry[i] = g5[i-1];
            end
            assign SUM[i] = p0[i] ^ carry[i];
        end
    endgenerate
endmodule

// Source: rtl/rtl/PC.v
module PC(clk, rst, write_enable, next_pc, pc);
    input  clk;
    input  rst;
    input  write_enable;
    input  [31:0] next_pc;
    output reg [31:0] pc;


always @(posedge clk or posedge rst) begin
    if (rst) begin
        pc <= 32'h0000_2000;
    end
    else if (write_enable) begin
        pc <= next_pc;
    end

end


endmodule

// Source: rtl/rtl/PipelineRegisters.v
module FetchDecodeRegisters(
    input         clk,
    input         rst,
    input         ready,
    input         kill,
    input  [31:0] if_stage_pc,
    input  [31:0] if_stage_pca4,
    input         if_stage_valid,
    input  [31:0] raw_instruction,
    input         if_access_fault,
    output reg [31:0] id_pca4,
    output reg [31:0] id_pc,
    output reg [31:0] id_ins,
    output reg        id_access_fault,
    output reg        id_valid
);

always @(posedge clk or posedge rst) begin
    if (rst) begin
        id_pca4         <= 32'b0;
        id_pc           <= 32'b0;
        id_ins          <= 32'b0;
        id_access_fault <= 1'b0;
        id_valid        <= 1'b0;
    end
    else begin
        if (kill) begin
            id_pca4         <= 32'b0;
            id_pc           <= 32'b0;
            id_ins          <= 32'b0;
            id_access_fault <= 1'b0;
            id_valid        <= 1'b0;
        end
        else if (ready) begin
            id_pca4         <= if_stage_pca4;
            id_pc           <= if_stage_pc;
            id_ins          <= raw_instruction;
            id_access_fault <= if_stage_valid && if_access_fault;
            id_valid        <= if_stage_valid;
        end
    end
end

endmodule

module DecodeExecuteRegisters(
    input         clk,
    input         rst,
    input         ready,
    input         kill,
    input  [31:0] id_pca4,
    input  [31:0] id_pc,
    input  [31:0] id_alu_b,
    input  [11:0] id_offset,
    input  [19:0] id_offset20,
    input  [4:0]  id_rd,
    input  [3:0]  id_aluop,
    input  [1:0]  id_wdsel,
    input         id_rfwrite,
    input         id_dmctrl,
    input         id_valid,
    input         id_branch,
    input         id_redirect_predicted,
    input  [1:0]  id_npcop,

    output reg [31:0] ex_pca4,
    output reg [31:0] ex_pc,
    output reg [31:0] ex_alu_b,
    output reg [11:0] ex_offset,
    output reg [19:0] ex_offset20,
    output reg [4:0]  ex_rd,
    output reg [3:0]  ex_aluop,
    output reg [1:0]  ex_wdsel,
    output reg        ex_rfwrite,
    output reg        ex_dmctrl,
    output reg        ex_valid,
    output reg        ex_branch,
    output reg        ex_redirect_predicted,
    output reg [1:0]  ex_npcop
);

always @(posedge clk or posedge rst) begin
    if (rst) begin
        ex_pca4     <= 32'b0;
        ex_pc       <= 32'b0;
        ex_alu_b    <= 32'b0;
        ex_offset   <= 12'b0;
        ex_offset20 <= 20'b0;
        ex_rd       <= 5'b0;
        ex_aluop    <= 4'b0;
        ex_wdsel    <= 2'b0;
        ex_rfwrite  <= 1'b0;
        ex_dmctrl   <= `DMCtrl_RD;
        ex_valid    <= 1'b0;
        ex_branch   <= 1'b0;
        ex_redirect_predicted <= 1'b0;
        ex_npcop    <= `NPC_PC;
    end
    else if (ready) begin
        if (kill) begin
            ex_pca4     <= 32'b0;
            ex_pc       <= 32'b0;
            ex_alu_b    <= 32'b0;
            ex_offset   <= 12'b0;
            ex_offset20 <= 20'b0;
            ex_rd       <= 5'b0;
            ex_aluop    <= 4'b0;
            ex_wdsel    <= 2'b0;
            ex_rfwrite  <= 1'b0;
            ex_dmctrl   <= `DMCtrl_RD;
            ex_valid    <= 1'b0;
            ex_branch   <= 1'b0;
            ex_redirect_predicted <= 1'b0;
            ex_npcop    <= `NPC_PC;
        end
        else begin
            ex_pca4     <= id_pca4;
            ex_pc       <= id_pc;
            ex_alu_b    <= id_alu_b;
            ex_offset   <= id_offset;
            ex_offset20 <= id_offset20;
            ex_rd       <= id_rd;
            ex_aluop    <= id_valid ? id_aluop : 4'b0;
            ex_wdsel    <= id_valid ? id_wdsel : 2'b0;
            ex_rfwrite  <= id_valid && id_rfwrite;
            ex_dmctrl   <= id_valid ? id_dmctrl : `DMCtrl_RD;
            ex_valid    <= id_valid;
            ex_branch   <= id_valid && id_branch;
            ex_redirect_predicted <= id_valid && id_redirect_predicted;
            ex_npcop    <= id_valid ? id_npcop : `NPC_PC;
        end
    end
end

endmodule

module ExecuteMemoryRegisters(
    input         clk,
    input         rst,
    input         ready,
    input         kill,
    input  [31:0] ex_store_data,
    input  [31:0] ex_pca4,
    input  [31:0] ex_pc,
    input  [4:0]  ex_rd,
    input  [1:0]  ex_wdsel,
    input         ex_rfwrite,
    input         ex_dmctrl,
    input         ex_valid,

    output reg [31:0] mem_store_data,
    output reg [31:0] mem_pca4,
    output reg [31:0] mem_pc,
    output reg [4:0]  mem_rd,
    output reg [1:0]  mem_wdsel,
    output reg        mem_rfwrite,
    output reg        mem_dmctrl,
    output reg        mem_valid
);

always @(posedge clk or posedge rst) begin
    if (rst) begin
        mem_store_data <= 32'b0;
        mem_pca4       <= 32'b0;
        mem_pc         <= 32'b0;
        mem_rd         <= 5'b0;
        mem_wdsel      <= 2'b0;
        mem_rfwrite    <= 1'b0;
        mem_dmctrl     <= `DMCtrl_RD;
        mem_valid      <= 1'b0;
    end
    else if (ready) begin
        if (kill) begin
            mem_store_data <= 32'b0;
            mem_pca4       <= 32'b0;
            mem_pc         <= 32'b0;
            mem_rd         <= 5'b0;
            mem_wdsel      <= 2'b0;
            mem_rfwrite    <= 1'b0;
            mem_dmctrl     <= `DMCtrl_RD;
            mem_valid      <= 1'b0;
        end
        else begin
            mem_store_data <= ex_store_data;
            mem_pca4       <= ex_pca4;
            mem_pc         <= ex_pc;
            mem_rd         <= ex_rd;
            mem_wdsel      <= ex_valid ? ex_wdsel : 2'b0;
            mem_rfwrite    <= ex_valid && ex_rfwrite;
            mem_dmctrl     <= ex_valid ? ex_dmctrl : `DMCtrl_RD;
            mem_valid      <= ex_valid;
        end
    end
end

endmodule

module MemoryWritebackRegisters(
    input         clk,
    input         rst,
    input         ready,
    input         kill,
    input  [31:0] mem_writeback_data,
    input  [4:0]  mem_rd,
    input         mem_rfwrite,
    input         mem_valid,

    output reg [31:0] wb_data,
    output reg [4:0]  wb_rd,
    output reg        wb_rfwrite,
    output reg        wb_valid
);

always @(posedge clk or posedge rst) begin
    if (rst) begin
        wb_data    <= 32'b0;
        wb_rd      <= 5'b0;
        wb_rfwrite <= 1'b0;
        wb_valid   <= 1'b0;
    end
    else begin
        if (!ready || kill) begin
            wb_data    <= 32'b0;
            wb_rd      <= 5'b0;
            wb_rfwrite <= 1'b0;
            wb_valid   <= 1'b0;
        end
        else begin
            wb_data    <= mem_writeback_data;
            wb_rd      <= mem_rd;
            wb_rfwrite <= mem_valid && mem_rfwrite;
            wb_valid   <= mem_valid;
        end
    end
end

endmodule

// Source: rtl/rtl/RF.v
module RF(
input [4:0] RR1,
input [4:0] RR2,
input [4:0] WR,
input [31:0] WD,
input RFWrite,
input clk,
output [31:0] RD1,
output [31:0] RD2,
output [31:0] RD1_raw,
output [31:0] RD2_raw,

input forward1,
input forward2,
input [31:0] FD1,  // forward data
input [31:0] FD2
);

reg [31:0] register [0:31];

always @(posedge clk) begin
  register[0] <= 32'h0;
  if ((WR != 0) && (RFWrite == 1)) begin
    register[WR] <= WD;
`ifdef DEBUG
    $display("R[00-07]=%8X %8X %8X %8X %8X %8X %8X %8X", 0, register[1], register[2], register[3], register[4], register[5], register[6], register[7]);
    $display("R[08-15]=%8X %8X %8X %8X %8X %8X %8X %8X", register[8], register[9], register[10], register[11], register[12], register[13], register[14], register[15]);
    $display("R[16-23]=%8X %8X %8X %8X %8X %8X %8X %8X", register[16], register[17], register[18], register[19], register[20], register[21], register[22], register[23]);
    $display("R[24-31]=%8X %8X %8X %8X %8X %8X %8X %8X", register[24], register[25], register[26], register[27], register[28], register[29], register[30], register[31]);
`endif
  end
end

assign RD1_raw = register[RR1];
assign RD2_raw = register[RR2];
assign RD1 = forward1 ? FD1 : RD1_raw;
assign RD2 = forward2 ? FD2 : RD2_raw;

`ifdef DIFFTEST

export "DPI-C" function DPI_getReg;
function int DPI_getReg(input int idx);
  return register[idx];
endfunction

`endif

endmodule

// Source: rtl/rtl/WishboneInstructionMaster.v
// Single-outstanding instruction master. It holds a Wishbone request stable
// until completion and drops a response when the fetch PC changed meanwhile.
module WishboneInstructionMaster(
    input         clk,
    input         rst,
    input         req_valid,
    input  [31:0] req_addr,

    output        rsp_valid,
    output        rsp_error,
    output [31:0] rsp_rdata,

    output [31:0] wb_adr_o,
    output [31:0] wb_dat_o,
    input  [31:0] wb_dat_i,
    output [3:0]  wb_sel_o,
    output        wb_we_o,
    output        wb_cyc_o,
    output        wb_stb_o,
    input         wb_ack_i,
    input         wb_err_i
);

reg        pending;
reg [31:0] pending_addr;

wire [31:0] active_addr;
wire        bus_request;
wire        bus_response;
wire        response_current;

assign active_addr      = pending ? pending_addr : req_addr;
assign bus_request      = pending || req_valid;
assign bus_response     = bus_request && (wb_ack_i || wb_err_i);
assign response_current = req_valid && (active_addr == req_addr);

assign rsp_valid = bus_response && response_current;
assign rsp_error = rsp_valid && wb_err_i;
assign rsp_rdata = wb_dat_i;

assign wb_adr_o = active_addr;
assign wb_dat_o = 32'b0;
assign wb_sel_o = 4'b1111;
assign wb_we_o  = 1'b0;
assign wb_cyc_o = bus_request;
assign wb_stb_o = bus_request;

always @(posedge clk or posedge rst) begin
    if (rst) begin
        pending      <= 1'b0;
        pending_addr <= 32'b0;
    end
    else if (pending) begin
        if (bus_response)
            pending <= 1'b0;
    end
    else if (req_valid && !bus_response) begin
        pending      <= 1'b1;
        pending_addr <= req_addr;
    end
end

endmodule

// Source: rtl/rtl/WishboneLocalRouter.v
// Routes one Wishbone master to a 4 KB local window or the external bus.
// Address, write data, byte enables, and write direction are shared directly
// with the local slave; only its request is gated by the address decode.
module WishboneLocalRouter #(
    parameter [19:0] LOCAL_PAGE = 20'h00000
)(
    input  [31:0] master_adr_i,
    input  [31:0] master_dat_i,
    input  [3:0]  master_sel_i,
    input         master_we_i,
    input         master_cyc_i,
    input         master_stb_i,
    output [31:0] master_dat_o,
    output        master_ack_o,
    output        master_err_o,

    output        local_cyc_o,
    output        local_stb_o,
    input  [31:0] local_dat_i,
    input         local_ack_i,
    input         local_err_i,

    output [31:0] external_adr_o,
    output [31:0] external_dat_o,
    output [3:0]  external_sel_o,
    output        external_we_o,
    output        external_cyc_o,
    output        external_stb_o,
    input  [31:0] external_dat_i,
    input         external_ack_i,
    input         external_err_i
);

wire local_selected;

assign local_selected = (master_adr_i[31:12] == LOCAL_PAGE);
assign local_cyc_o = master_cyc_i && local_selected;
assign local_stb_o = master_stb_i && local_selected;

assign master_dat_o = local_selected ? local_dat_i : external_dat_i;
assign master_ack_o = local_selected ? local_ack_i : external_ack_i;
assign master_err_o = local_selected ? local_err_i : external_err_i;

assign external_adr_o = master_adr_i;
assign external_dat_o = master_dat_i;
assign external_sel_o = master_sel_i;
assign external_we_o = master_we_i;
assign external_cyc_o = master_cyc_i && !local_selected;
assign external_stb_o = master_stb_i && !local_selected;

endmodule

// Source: rtl/rtl/WishboneMaster.v
// Combinational Wishbone B4 Classic adapter. Requesters in this core keep
// req_valid, address, and write data stable until rsp_valid is asserted.
module WishboneMaster(
    input         req_valid,
    input  [31:0] req_addr,
    input  [31:0] req_wdata,
    input  [3:0]  req_sel,
    input         req_we,

    output        rsp_valid,
    output        rsp_error,
    output [31:0] rsp_rdata,

    output [31:0] wb_adr_o,
    output [31:0] wb_dat_o,
    input  [31:0] wb_dat_i,
    output [3:0]  wb_sel_o,
    output        wb_we_o,
    output        wb_cyc_o,
    output        wb_stb_o,
    input         wb_ack_i,
    input         wb_err_i
);

assign rsp_valid = req_valid && (wb_ack_i || wb_err_i);
assign rsp_error = req_valid && wb_err_i;
assign rsp_rdata = wb_dat_i;

assign wb_adr_o = req_addr;
assign wb_dat_o = req_wdata;
assign wb_sel_o = req_sel;
assign wb_we_o  = req_we;
assign wb_cyc_o = req_valid;
assign wb_stb_o = req_valid;

endmodule

// Source: rtl/rtl/WishboneInstructionMemory.v
// Wishbone slave wrapper for the local 64-bit instruction SRAM. Two line
// buffers form a sequential stream buffer: while one line is consumed, the
// next line is read from SRAM. There is no general-purpose cache or refill
// replacement policy.
module WishboneInstructionMemory(
    input         clk,
    input         rst,
    input  [31:0] wb_adr_i,
    input         wb_cyc_i,
    input         wb_stb_i,
    input         fetch_valid_i,
    input  [31:0] fetch_addr_i,
    output [31:0] wb_dat_o,
    output        wb_ack_o,
    output        wb_err_o
);

localparam STATE_IDLE     = 2'b00;
localparam STATE_WAIT     = 2'b01;
localparam STATE_COMPLETE = 2'b10;

reg [1:0]  state;
reg [8:0]  read_line_index;
reg [8:0]  read_next_line_index;
reg        read_line_has_next;
reg        read_buffer_select;
reg        replacement_select;
reg [8:0]  line0_index;
reg [8:0]  line1_index;
reg [8:0]  line0_next_index;
reg [8:0]  line1_next_index;
reg        line0_valid;
reg        line1_valid;
reg        line0_has_next;
reg        line1_has_next;
reg [63:0] line0_data;
reg [63:0] line1_data;

reg        launch_read;
reg [8:0]  launch_line_index;
reg        launch_buffer_select;

wire       wb_request;
wire [8:0] wb_line_index;
wire [8:0] fetch_line_index;
wire       line0_hit;
wire       line1_hit;
wire       buffered_hit;
wire       completing_hit;
wire [63:0] selected_line_data;
wire       fetch_line0_hit;
wire       fetch_line1_hit;
wire       fetch_buffered_hit;
wire       line0_prefetch_needed;
wire       line1_prefetch_needed;
wire [8:0] sequential_line_index;
wire       sequential_line_in_range;
wire [63:0] sram_line_data;

assign wb_request      = wb_cyc_i && wb_stb_i;
assign wb_line_index   = wb_adr_i[11:3];
assign fetch_line_index = fetch_addr_i[11:3];
assign line0_hit       = line0_valid && (wb_line_index == line0_index);
assign line1_hit       = line1_valid && (wb_line_index == line1_index);
assign buffered_hit       = line0_hit || line1_hit;
assign completing_hit     = (state == STATE_COMPLETE) &&
                            (wb_line_index == read_line_index);
assign selected_line_data = line0_hit ? line0_data :
                            line1_hit ? line1_data : sram_line_data;
assign fetch_line0_hit    = line0_valid &&
                            (fetch_line_index == line0_index);
assign fetch_line1_hit    = line1_valid &&
                            (fetch_line_index == line1_index);
assign fetch_buffered_hit = fetch_line0_hit || fetch_line1_hit;
assign line0_prefetch_needed = line0_has_next &&
                               !(line1_valid &&
                                 (line1_index == line0_next_index));
assign line1_prefetch_needed = line1_has_next &&
                               !(line0_valid &&
                                 (line0_index == line1_next_index));
assign sequential_line_index = fetch_line0_hit ? line0_next_index
                                                : line1_next_index;
assign sequential_line_in_range =
    (fetch_line0_hit && line0_prefetch_needed) ||
    (fetch_line1_hit && line1_prefetch_needed);

assign wb_ack_o = wb_request && (buffered_hit || completing_hit);
assign wb_err_o = 1'b0;
assign wb_dat_o = wb_adr_i[2] ? selected_line_data[63:32]
                              : selected_line_data[31:0];

// A redirecting FETCH_PC has priority over continuing a stale stream.
always @(*) begin
    launch_read          = 1'b0;
    launch_line_index    = 9'b0;
    launch_buffer_select = replacement_select;

    if (state == STATE_IDLE) begin
        if (fetch_valid_i && !fetch_buffered_hit) begin
            launch_read          = 1'b1;
            launch_line_index    = fetch_line_index;
            launch_buffer_select = replacement_select;
        end
        else if (fetch_valid_i && sequential_line_in_range) begin
            launch_read          = 1'b1;
            launch_line_index    = sequential_line_index;
            launch_buffer_select = fetch_line0_hit ? 1'b1 : 1'b0;
        end
        else if (wb_request && !buffered_hit) begin
            launch_read          = 1'b1;
            launch_line_index    = wb_line_index;
            launch_buffer_select = replacement_select;
        end
    end
    else if (state == STATE_COMPLETE && fetch_valid_i) begin
        if ((fetch_line_index != read_line_index) &&
            !fetch_buffered_hit) begin
            launch_read          = 1'b1;
            launch_line_index    = fetch_line_index;
            launch_buffer_select = ~read_buffer_select;
        end
        else if ((fetch_line_index == read_line_index) &&
                 read_line_has_next) begin
            launch_read          = 1'b1;
            launch_line_index    = read_next_line_index;
            launch_buffer_select = ~read_buffer_select;
        end
    end
end

IM U_IM (
    .clk(clk),
    .rst(rst),
    .enable(launch_read),
    .addr(launch_line_index),
    .data(sram_line_data)
);

`ifdef DIFFTEST
import "DPI-C" function void instructionWishboneCheck(
    input int addr,
    input int read_data
);
`endif

always @(posedge clk or posedge rst) begin
    if (rst) begin
        state                <= STATE_IDLE;
        read_line_index      <= 9'b0;
        read_next_line_index <= 9'b0;
        read_line_has_next   <= 1'b0;
        read_buffer_select   <= 1'b0;
        replacement_select   <= 1'b0;
        line0_index          <= 9'b0;
        line1_index          <= 9'b0;
        line0_next_index     <= 9'b0;
        line1_next_index     <= 9'b0;
        line0_valid          <= 1'b0;
        line1_valid          <= 1'b0;
        line0_has_next       <= 1'b0;
        line1_has_next       <= 1'b0;
        line0_data           <= 64'b0;
        line1_data           <= 64'b0;
    end
    else begin
`ifdef DIFFTEST
        if (wb_ack_o)
            instructionWishboneCheck(wb_adr_i, wb_dat_o);
`endif

        case (state)
        STATE_IDLE: begin
            if (launch_read) begin
                state              <= STATE_WAIT;
                read_line_index    <= launch_line_index;
                read_next_line_index <= launch_line_index + 9'd1;
                read_line_has_next <= (launch_line_index != 9'h1ff);
                read_buffer_select <= launch_buffer_select;
            end
        end
        STATE_WAIT: begin
            state <= STATE_COMPLETE;
        end
        STATE_COMPLETE: begin
            if (read_buffer_select) begin
                line1_index   <= read_line_index;
                line1_next_index <= read_next_line_index;
                line1_valid   <= 1'b1;
                line1_has_next <= read_line_has_next;
                line1_data    <= sram_line_data;
            end
            else begin
                line0_index   <= read_line_index;
                line0_next_index <= read_next_line_index;
                line0_valid   <= 1'b1;
                line0_has_next <= read_line_has_next;
                line0_data    <= sram_line_data;
            end
            replacement_select <= ~read_buffer_select;

            if (launch_read) begin
                state              <= STATE_WAIT;
                read_line_index    <= launch_line_index;
                read_next_line_index <= launch_line_index + 9'd1;
                read_line_has_next <= (launch_line_index != 9'h1ff);
                read_buffer_select <= launch_buffer_select;
                if (launch_buffer_select)
                    line1_valid <= 1'b0;
                else
                    line0_valid <= 1'b0;
            end
            else begin
                state <= STATE_IDLE;
            end
        end
        default: begin
            state <= STATE_IDLE;
        end
        endcase
    end
end

endmodule

// Source: rtl/rtl/WishboneDataMemory.v
// Wishbone slave wrapper for the local 32-bit data SRAM.
module WishboneDataMemory(
    input         clk,
    input         rst,
    input  [31:0] wb_adr_i,
    input  [31:0] wb_dat_i,
    input  [3:0]  wb_sel_i,
    input         wb_we_i,
    input         wb_cyc_i,
    input         wb_stb_i,
    output [31:0] wb_dat_o,
    output        wb_ack_o,
    output        wb_err_o
);

localparam STATE_IDLE = 2'b00;
localparam STATE_WAIT = 2'b01;
localparam STATE_ACK  = 2'b10;

reg [1:0]  state;
reg [31:0] address;
reg [31:0] write_data;
reg [3:0]  byte_select;
reg        write_enable;
wire       start;
wire       immediate_store;
wire [31:0] memory_data;

assign start    = wb_cyc_i && wb_stb_i && (state == STATE_IDLE);
assign immediate_store = start && wb_we_i;
// A store is committed on its request edge and may therefore complete as a
// zero-wait Wishbone transfer. Loads retain the cycles required by SRAM CLK-Q.
assign wb_ack_o = (immediate_store && (wb_sel_i == 4'b1111)) ||
                  ((state == STATE_ACK) && !write_enable &&
                   (byte_select == 4'b1111));
assign wb_err_o = (immediate_store && (wb_sel_i != 4'b1111)) ||
                  ((state == STATE_ACK) && !write_enable &&
                   (byte_select != 4'b1111));
assign wb_dat_o = memory_data;

DM U_DM (
    .clk(clk),
    .addr(wb_adr_i[11:2]),
    .write_data(wb_dat_i),
    .write_enable(start && wb_we_i && (wb_sel_i == 4'b1111)),
    .read_data(memory_data)
);

`ifdef DIFFTEST
import "DPI-C" function void dataWishboneCheck(
    input int addr,
    input int write_data,
    input int read_data,
    input bit write_enable
);
`endif

always @(posedge clk or posedge rst) begin
    if (rst) begin
        state        <= STATE_IDLE;
        address      <= 32'b0;
        write_data   <= 32'b0;
        byte_select  <= 4'b0;
        write_enable <= 1'b0;
    end
    else begin
        case (state)
        STATE_IDLE: begin
            if (immediate_store) begin
`ifdef DIFFTEST
                if (wb_sel_i == 4'b1111)
                    dataWishboneCheck(wb_adr_i, wb_dat_i, wb_dat_o, 1'b1);
`endif
            end
            else if (start) begin
                state        <= STATE_WAIT;
                address      <= wb_adr_i;
                write_data   <= wb_dat_i;
                byte_select  <= wb_sel_i;
                write_enable <= wb_we_i;
            end
        end
        STATE_WAIT: begin
            state <= STATE_ACK;
        end
        STATE_ACK: begin
`ifdef DIFFTEST
            if (byte_select == 4'b1111)
                dataWishboneCheck(address, write_data, wb_dat_o,
                                  write_enable);
`endif
            state <= STATE_IDLE;
        end
        default: begin
            state <= STATE_IDLE;
        end
        endcase
    end
end

endmodule

// Source: rtl/rtl/riscv.v
//////////////////////////////////////////////////////////////////////////////////
// Company:
// Engineer:
//
// Create Date: 2024/11/22 13:30:25
// Design Name:
// Module Name: riscv
// Project Name:
// Target Devices:
// Tool Versions:
// Description:
//
// Dependencies:
//
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
//
//////////////////////////////////////////////////////////////////////////////////
module riscv(clk, rst, RD, out_ins, trap, trap_cause, trap_epc, trap_tval,
  iwb_adr_o, iwb_dat_o, iwb_dat_i, iwb_sel_o, iwb_we_o,
  iwb_cyc_o, iwb_stb_o, iwb_ack_i, iwb_err_i,
  dwb_adr_o, dwb_dat_o, dwb_dat_i, dwb_sel_o, dwb_we_o,
  dwb_cyc_o, dwb_stb_o, dwb_ack_i, dwb_err_i
`ifdef DIFFTEST
, done
`endif
);
input clk, rst;
output [31:0] RD;
output [31:0] out_ins;
output trap;
output [3:0] trap_cause;
output [31:0] trap_epc;
output [31:0] trap_tval;

output [31:0] iwb_adr_o;
output [31:0] iwb_dat_o;
input  [31:0] iwb_dat_i;
output [3:0]  iwb_sel_o;
output        iwb_we_o;
output        iwb_cyc_o;
output        iwb_stb_o;
input         iwb_ack_i;
input         iwb_err_i;
output [31:0] dwb_adr_o;
output [31:0] dwb_dat_o;
input  [31:0] dwb_dat_i;
output [3:0]  dwb_sel_o;
output        dwb_we_o;
output        dwb_cyc_o;
output        dwb_stb_o;
input         dwb_ack_i;
input         dwb_err_i;

`ifdef DIFFTEST
output done;
`endif

wire RFWrite, DMCtrl, PCWrite, InsMemRW;
wire [1:0] NPCOp;
wire [3:0] ALUOp;
wire [31:0] PC, NPC, PCA4;
wire [31:0] in_ins, DR_out;
wire [4:0] WR;
wire [31:0] RD1, RD1_r, RD2, RD2_r;
wire [31:0] RD1_raw, RD2_raw;
wire [31:0] A, B, ALU_result, ALU_result_r;

/* pipeline interconnect */
wire [31:0] PC_NPC, NPC_PC;
wire [31:0] FETCH_PC;
wire [19:0] NPC_EX_Offset20;
wire [11:0] NPC_EX_Offset12;
wire [4:0]  WB_rd;
wire forward1, forward2;
wire [31:0] FD1, FD2;
wire [31:0] EX_ALU_B;
wire [31:0] RF_WD;
wire [31:0] DM_WD;
wire [31:0] NPC_taken_p4;
wire [4:0]  ID_rs1, ID_rs2;
wire IF_ready, IF_error, DM_ready, DM_error;
wire mem_hold;
wire DMReq;

wire [31:0] im_adr;
wire [31:0] im_dat_o;
wire [31:0] im_dat_i;
wire [3:0]  im_sel;
wire        im_we;
wire        im_cyc;
wire        im_stb;
wire        im_ack;
wire        im_err;
wire        im_local_cyc;
wire        im_local_stb;
wire [31:0] im_local_data;
wire        im_local_ack;
wire        im_local_err;

wire [31:0] dm_adr;
wire [31:0] dm_dat_o;
wire [31:0] dm_dat_i;
wire [3:0]  dm_sel;
wire        dm_we;
wire        dm_cyc;
wire        dm_stb;
wire        dm_ack;
wire        dm_err;
wire        dm_local_cyc;
wire        dm_local_stb;
wire [31:0] dm_local_data;
wire        dm_local_ack;
wire        dm_local_err;

ControlUnit U_ControlUnit(
    .clk(clk), .rst(rst), .instruction(in_ins),
    .RFWrite(RFWrite), .DMCtrl(DMCtrl), .PCWrite(PCWrite), .InsMemRW(InsMemRW),
    .ALUOp(ALUOp), .NPCOp(NPCOp),
    .PC(PC), .PCA4(PCA4),
    .NPC(NPC), .NPC_taken_p4(NPC_taken_p4),
    .RD2(RD2),
    .RD1_raw(RD1_raw), .RD2_raw(RD2_raw),
    .ALU_result(ALU_result), .ALU_result_r(ALU_result_r),
    .DM_RD(DR_out),
    .RD2_r(RD2_r),
    .IF_ready(IF_ready), .IF_error(IF_error),
    .DM_ready(DM_ready), .DM_error(DM_error),

    .mem_hold(mem_hold),
    .PC_NPC(PC_NPC), .NPC_PC(NPC_PC),
    .FETCH_PC(FETCH_PC),
    .NPC_EX_Offset12(NPC_EX_Offset12), .NPC_EX_Offset20(NPC_EX_Offset20),
    .WB_rd_out(WB_rd),
    .forward1(forward1), .forward2(forward2), .FD1(FD1), .FD2(FD2),
    .RF_WD(RF_WD), .ID_rs1_out(ID_rs1), .ID_rs2_out(ID_rs2),
    .EX_ALU_B(EX_ALU_B), .DM_WD(DM_WD),
    .DMReq(DMReq),
    .trap(trap), .trap_cause(trap_cause), .trap_epc(trap_epc), .trap_tval(trap_tval)


`ifdef DIFFTEST
    , .done(done)
`endif


);

PC U_PC (
    .clk(clk), .rst(rst), .write_enable(PCWrite),
    .next_pc(PC_NPC), .pc(PC)
);

NPC U_NPC (
    .PC(PC), .NPCOp(NPCOp), .PCA4(PCA4), .NPC(NPC),
    .NPC_PC(NPC_PC), .NPC_Offset12(NPC_EX_Offset12), .NPC_Offset20(NPC_EX_Offset20), .NPC_rs(RD1_r),
    .NPC_taken_p4(NPC_taken_p4)
);

WishboneInstructionMaster U_InstructionWishboneMaster (
    .clk(clk), .rst(rst),
    .req_valid(InsMemRW), .req_addr(FETCH_PC),
    .rsp_valid(IF_ready), .rsp_error(IF_error), .rsp_rdata(in_ins),
    .wb_adr_o(im_adr), .wb_dat_o(im_dat_o), .wb_dat_i(im_dat_i),
    .wb_sel_o(im_sel), .wb_we_o(im_we),
    .wb_cyc_o(im_cyc), .wb_stb_o(im_stb),
    .wb_ack_i(im_ack), .wb_err_i(im_err)
);

WishboneInstructionMemory U_InstructionMemorySlave (
    .clk(clk), .rst(rst),
    .wb_adr_i(im_adr),
    .wb_cyc_i(im_local_cyc), .wb_stb_i(im_local_stb),
    .fetch_valid_i(InsMemRW && (FETCH_PC[31:12] == 20'h00002)),
    .fetch_addr_i(FETCH_PC),
    .wb_dat_o(im_local_data), .wb_ack_o(im_local_ack),
    .wb_err_o(im_local_err)
);

WishboneLocalRouter #(.LOCAL_PAGE(20'h00002)) U_InstructionBusRouter (
    .master_adr_i(im_adr), .master_dat_i(im_dat_o),
    .master_sel_i(im_sel), .master_we_i(im_we),
    .master_cyc_i(im_cyc), .master_stb_i(im_stb),
    .master_dat_o(im_dat_i), .master_ack_o(im_ack),
    .master_err_o(im_err),
    .local_cyc_o(im_local_cyc), .local_stb_o(im_local_stb),
    .local_dat_i(im_local_data), .local_ack_i(im_local_ack),
    .local_err_i(im_local_err),
    .external_adr_o(iwb_adr_o), .external_dat_o(iwb_dat_o),
    .external_sel_o(iwb_sel_o), .external_we_o(iwb_we_o),
    .external_cyc_o(iwb_cyc_o), .external_stb_o(iwb_stb_o),
    .external_dat_i(iwb_dat_i), .external_ack_i(iwb_ack_i),
    .external_err_i(iwb_err_i)
);

assign out_ins = in_ins;

RF U_RF (
    .RR1(ID_rs1), .RR2(ID_rs2), .WR(WR), .WD(RF_WD), .clk(clk),
    .RFWrite(RFWrite), .RD1(RD1), .RD2(RD2),
    .RD1_raw(RD1_raw), .RD2_raw(RD2_raw),
    .forward1(forward1), .forward2(forward2),
    .FD1(FD1), .FD2(FD2)
);

assign WR = WB_rd;

Flopr U_A (
    .clk(clk), .rst(rst), .in_data(mem_hold ? RD1_r : RD1), .out_data(RD1_r)
);

Flopr U_B (
    .clk(clk), .rst(rst), .in_data(mem_hold ? RD2_r : RD2), .out_data(RD2_r)
);

assign A = RD1_r;
assign B = EX_ALU_B;

ALU U_ALU (
    .A(A), .B(B), .ALUOp(ALUOp), .ALU_result(ALU_result)
);

Flopr U_ALUOut (
    .clk(clk), .rst(rst),
    .in_data(mem_hold ? ALU_result_r : ALU_result),
    .out_data(ALU_result_r)
);

WishboneMaster U_DataWishboneMaster (
    .req_valid(DMReq),
    .req_addr(ALU_result_r), .req_wdata(DM_WD),
    .req_sel(4'b1111), .req_we(DMCtrl),
    .rsp_valid(DM_ready), .rsp_error(DM_error), .rsp_rdata(DR_out),
    .wb_adr_o(dm_adr), .wb_dat_o(dm_dat_o), .wb_dat_i(dm_dat_i),
    .wb_sel_o(dm_sel), .wb_we_o(dm_we),
    .wb_cyc_o(dm_cyc), .wb_stb_o(dm_stb),
    .wb_ack_i(dm_ack), .wb_err_i(dm_err)
);

WishboneDataMemory U_DataMemorySlave (
    .clk(clk), .rst(rst),
    .wb_adr_i(dm_adr), .wb_dat_i(dm_dat_o), .wb_sel_i(dm_sel),
    .wb_we_i(dm_we), .wb_cyc_i(dm_local_cyc),
    .wb_stb_i(dm_local_stb),
    .wb_dat_o(dm_local_data), .wb_ack_o(dm_local_ack),
    .wb_err_o(dm_local_err)
);

WishboneLocalRouter #(.LOCAL_PAGE(20'h00000)) U_DataBusRouter (
    .master_adr_i(dm_adr), .master_dat_i(dm_dat_o),
    .master_sel_i(dm_sel), .master_we_i(dm_we),
    .master_cyc_i(dm_cyc), .master_stb_i(dm_stb),
    .master_dat_o(dm_dat_i), .master_ack_o(dm_ack),
    .master_err_o(dm_err),
    .local_cyc_o(dm_local_cyc), .local_stb_o(dm_local_stb),
    .local_dat_i(dm_local_data), .local_ack_i(dm_local_ack),
    .local_err_i(dm_local_err),
    .external_adr_o(dwb_adr_o), .external_dat_o(dwb_dat_o),
    .external_sel_o(dwb_sel_o), .external_we_o(dwb_we_o),
    .external_cyc_o(dwb_cyc_o), .external_stb_o(dwb_stb_o),
    .external_dat_i(dwb_dat_i), .external_ack_i(dwb_ack_i),
    .external_err_i(dwb_err_i)
);

assign RD = DR_out;


endmodule
